### ISSUE TITLE
chore: update angular to v14

### ISSUE THREAD

**Issue by aaa123eee** [flowup/contentful-rich-text-angular-renderer#1]
It would be awesome if you can publish a new version so we can avoid problems with peer deps

<img width="742" alt="Screenshot 2022-08-11 at 11 52 16" src="https://user-images.githubusercontent.com/20088530/184088487-f0313b33-28ac-4b59-8f3a-134fbf354c3e.png">

**Comment by vmasek** [comment]
Updated to Angular 15 and released in version `0.5.0`
